export const ROOT_URL = 'https://server-wheoqsnils.now.sh'

export const LOAD_STORIES_REQUEST = 'LOAD_STORIES_REQUEST'
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS'
export const LOAD_STORIES_ERROR = 'LOAD_STORIES_ERROR'

export const REFRESH_STORIES_REQUEST = 'REFRESH_STORIES_REQUEST'
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS'
export const REFRESH_STORIES_ERROR = 'REFRESH_STORIES_ERROR'

export const LOAD_COMMENTS_REQUEST = 'LOAD_COMMENTS_REQUEST'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_ERROR = 'LOAD_COMMENTS_ERROR'

export const LOAD_SUB_COMMENTS_REQUEST = 'LOAD_SUB_COMMENTS_REQUEST'
export const LOAD_SUB_COMMENTS_SUCCESS = 'LOAD_SUB_COMMENTS_SUCCESS'
export const LOAD_SUB_COMMENTS_ERROR = 'LOAD_SUB_COMMENTS_ERROR'
