export const ROOT_URL = 'https://hacker-news.firebaseio.com/v0'

export const LOAD_STORIES_REQUEST = 'LOAD_STORIES_REQUEST'
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS'
export const LOAD_STORIES_ERROR = 'LOAD_STORIES_ERROR'

export const REFRESH_STORIES_REQUEST = 'REFRESH_STORIES_REQUEST'
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS'
export const REFRESH_STORIES_ERROR = 'REFRESH_STORIES_ERROR'
