export const ROOT_URL = "http://localhost:3000"

export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS'
export const LOAD_SETTINGS_ERROR = 'LOAD_SETTINGS_ERROR'

export const CHANGE_VIEW = 'CHANGE_VIEW'

export const FETCH_TOPIC_STORIES_REQUEST = 'FETCH_TOPIC_STORIES_REQUEST'
export const FETCH_TOPIC_STORIES_SUCCESS = 'FETCH_TOPIC_STORIES_SUCCESS'
export const FETCH_TOPIC_STORIES_ERROR = 'FETCH_TOPIC_STORIES_ERROR'

export const FETCH_SAVED_STORIES_REQUEST = 'FETCH_SAVED_STORIES_REQUEST'
export const FETCH_SAVED_STORIES_SUCCESS = 'FETCH_SAVED_STORIES_SUCCESS'
export const FETCH_SAVED_STORIES_ERROR = 'FETCH_SAVED_STORIES_ERROR'

export const SAVE_STORY_SUCCESS = 'SAVE_STORY_SUCCESS'
export const SAVE_STORY_ERROR = 'SAVE_STORY_ERROR'
